config/routes.rb
Nextlist::Application.routes.draw do
  

  get "home/index"
  resources :users
  resources :messages
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
 
  scope :api do
    get "/users(.:format)" => "users#index"
    get "/users/:id(.:format)" => "users#show"
    get "/posts(.:format)" => "posts#index"
    get "/posts/:id(.:format)" => "posts#show"
    get "/messages(.:format)" => "messages#index"
    get "/posts/:id(.:format)" => "messages#show"
  end
  
  root to: "home#index"
  get '/users/users_index(.:format)'
  match '/users_index',  to: 'users#users_index',            via: 'get'
  
  get '/posts/posts_index(.:format)'
  match '/posts_index',  to: 'posts#posts_index',            via: 'get'
  
  get '/home/posting_board(.:format)'
  match '/posting_board',  to: 'home#posting_board',            via: 'get'
  
  get '/home/user_board(.:format)'
  match '/user_board',  to: 'home#user_board',            via: 'get'
  
  match '/profile/(:id)',  to: 'users#profile',
      :as => :profile, 
      :via => :get
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="NextList">
<head>
  <title>20sTimes</title>
  

 

  
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular-resource.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  
  <%= javascript_include_tag "application" %>
   <script>
    $(document).on('page:load', function() {
      return $('[ng-app]').each(function() {
        var module;
        module = $(this).attr('ng-app');
        return angular.bootstrap(this, [module]);
      });
    });
  </script>
  

  <%= csrf_meta_tags %>
</head>
<body>


    <div class="navbar navbar-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a id = "navlogo" class="navbar-brand" href=<%= root_path %>>the<b>Twenties</b>Times</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href=<%= posting_board_path %>>Articles</a></li>
            <li><a href=<%= user_board_path %>>Authors</a></li>
            <li><a ng-click="changeView()">About Us</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
	    <% if signed_in? %>
	      <% if current_user.admin? %>
	      <li><a href=<%= profile_path(current_user.id) %>>Profile</a></li>
	      <li><a href=<%= users_index_path %>>Users</a></li>
	      <li><a href=<%= posts_index_path %>>Posts</a></li>
	      <% end %>
	      <li><%= link_to "Sign Out", signout_path, method: "DELETE" %></li>
	    <% else %>
	      <li><a href=<%= signin_path %>>Sign In</a></li>
	    <% end %>
	  </ul>
        </div>
      </div>
    </div>
    
    <% if signed_in? %>
        <div id = "div-current-user" data-user-id="<%= @current_user.id %>" data-user-name="<%= @current_user.name %>" data-user-email="<%= @current_user.email %>"></div>
    <% end %>
    
    </br>
    <div>
        <%= yield %>
    </div>

    <div class="navbar navbar-default navbar-fixed-bottom" role="navigation">
      <div class="container">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Created by Raj Maitra</a></li>
          </ul>
        </div>
      </div>
    </div>
    
</br>
    </br>
    </br>
  
</body>
</html>